version: '3'
services:
  mongodb:
    container_name: mongodb-container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - contability-network
      
volumes:
  mongodb_data:

networks:
  contability-network:
    driver: bridge